-- Inserção de usuários

INSERT INTO usuarios (nm_usuario, email) VALUES
('Ana Sophia Araújo', 'levicunha@ig.com.br'),
('Renan Viana', 'bazevedo@da.com'),
('Catarina Viana', 'ana-liviafreitas@gmail.com'),
('Samuel Pereira', 'henrique35@gmail.com'),
('João Miguel Castro', 'kamilly40@ig.com.br'),
('Maria Alice Costa', 'vieiranicolas@ig.com.br'),
('Isabelly da Mota', 'diassophia@cardoso.net'),
('João Miguel Freitas', 'igor55@hotmail.com'),
('Emanuelly Cardoso', 'igorrezende@fogaca.net'),
('Giovanna Caldeira', 'lopesalana@campos.net'),
('Raquel Lopes', 'pnovaes@da.org'),
('Felipe Teixeira', 'xnunes@hotmail.com'),
('Luiz Gustavo Sales', 'correiahenrique@pereira.br'),
('Letícia Souza', 'correiamaria-julia@bol.com.br'),
('Vitor Mendes', 'ana-julia27@ferreira.com'),
('Ana Lívia Jesus', 'viniciusda-cruz@martins.com'),
('João Guilherme Lima', 'duarteisabel@cardoso.br'),
('Vitor Hugo Teixeira', 'marcelaribeiro@ferreira.br'),
('Marcelo da Paz', 'cmoura@bol.com.br'),
('Ana Vitória Farias', 'mendesaugusto@das.com'),
('Bernardo Azevedo', 'silvalucas@yahoo.com.br'),
('Luiza da Rosa', 'yfarias@oliveira.net'),
('Caio Pinto', 'doliveira@ig.com.br'),
('Renan Castro', 'zmendes@farias.net'),
('Lavínia Cunha', 'matheusrezende@hotmail.com'),
('Leonardo Vieira', 'vianaantonio@duarte.br'),
('Luana da Rosa', 'da-cunhavitor-hugo@gmail.com'),
('Emanuella Ramos', 'jrodrigues@hotmail.com'),
('Enrico Caldeira', 'carlos-eduardo09@santos.com'),
('Luiz Gustavo Cardoso', 'camposmaria-eduarda@nunes.net'),
('Maria Vitória Barbosa', 'usilveira@da.br'),
('Francisco Novaes', 'ana51@ramos.com'),
('Luiz Otávio da Rosa', 'samuelcampos@hotmail.com'),
('Dr. Davi Lucca Pires', 'vieiranoah@ig.com.br'),
('Daniel Ferreira', 'vieirahenrique@gomes.net'),
('Sra. Cecília Ferreira', 'calebe16@yahoo.com.br'),
('Alexandre Melo', 'igor78@alves.com'),
('Ryan da Costa', 'isis82@costela.com'),
('João Guilherme Barbosa', 'maria-juliafarias@ig.com.br'),
('João Gabriel Oliveira', 'igorda-luz@araujo.com'),
('Sra. Valentina Oliveira', 'ian16@ribeiro.net'),
('Isabel Lima', 'benjaminda-mota@melo.org'),
('Vitor Freitas', 'vteixeira@gmail.com'),
('Francisco da Luz', 'cavalcantijuliana@uol.com.br'),
('Dr. Leandro Silva', 'qda-mota@pinto.net'),
('Dr. Bernardo Melo', 'jesusclarice@yahoo.com.br'),
('Júlia Martins', 'gabrielly23@uol.com.br'),
('Isis da Luz', 'avieira@yahoo.com.br'),
('Emanuel Pinto', 'cpires@ig.com.br'),
('Luiz Gustavo Ribeiro', 'gomeseduarda@carvalho.net'),
('Gabriela das Neves', 'benjaminbarbosa@ribeiro.br'),
('Maria Julia da Mota', 'pnunes@hotmail.com'),
('Olivia Almeida', 'ldas-neves@barros.net'),
('Lorenzo Cunha', 'rebeca79@ig.com.br'),
('Lara Vieira', 'pietraribeiro@uol.com.br'),
('Vitor Gabriel Farias', 'rduarte@uol.com.br'),
('Theo Gomes', 'raul58@cunha.net'),
('Olivia da Costa', 'peixotoalice@viana.br'),
('Ana Carolina da Rocha', 'waragao@bol.com.br'),
('Luana Almeida', 'raquel66@bol.com.br'),
('Dra. Maria Cecília das Neves', 'marcelopinto@uol.com.br'),
('João Pedro Mendes', 'biancacostela@bol.com.br'),
('Alice Novaes', 'pereiragabriel@da.com'),
('João Miguel Martins', 'vmartins@freitas.br'),
('Bruno Ribeiro', 'monteirolevi@barbosa.net'),
('Anthony da Costa', 'brunacorreia@rezende.com'),
('Maria Correia', 'enrico90@nascimento.br'),
('Srta. Ana Julia Farias', 'maria-luiza91@monteiro.br'),
('Isadora Campos', 'peixotocaroline@gmail.com'),
('Isabelly Ramos', 'uda-luz@teixeira.br'),
('Larissa Fogaça', 'davifreitas@uol.com.br'),
('Vitor Gabriel Rezende', 'benicio75@hotmail.com'),
('Clara Moraes', 'matheus94@bol.com.br'),
('Luiz Henrique da Mota', 'milenaoliveira@duarte.br'),
('Raquel Rodrigues', 'carvalhonicolas@hotmail.com'),
('Olivia Farias', 'bruna88@yahoo.com.br'),
('Sofia Vieira', 'mariana74@yahoo.com.br'),
('Enzo Costa', 'erick82@da.org'),
('Diogo Gonçalves', 'joao-gabriel40@freitas.org'),
('Srta. Maysa Rodrigues', 'gomesbrenda@pires.br'),
('Benjamin Fernandes', 'camposalana@uol.com.br'),
('Murilo Barros', 'heloisajesus@farias.br'),
('Maria Vitória das Neves', 'tpires@bol.com.br'),
('Gabriela Caldeira', 'leticiada-rosa@cardoso.com'),
('Davi Vieira', 'alexandreoliveira@ribeiro.org'),
('Enzo Gomes', 'rcardoso@hotmail.com'),
('Yuri da Paz', 'vianalevi@ig.com.br'),
('Gabriel da Conceição', 'da-cunhavitoria@gomes.br'),
('Lucas Gabriel Jesus', 'clara87@uol.com.br'),
('Noah Barbosa', 'kamilly40@gmail.com'),
('Renan Aragão', 'da-luzbrenda@bol.com.br'),
('Laura Freitas', 'frodrigues@monteiro.br'),
('Dr. Raul Cavalcanti', 'alicia74@vieira.com'),
('Ana Laura Lopes', 'enzo68@gmail.com'),
('Maria Cecília Rezende', 'da-motaelisa@yahoo.com.br'),
('Sophia Sales', 'da-rochaluiz-otavio@bol.com.br'),
('Gustavo Henrique Pires', 'araujolorena@bol.com.br'),
('Thales da Cruz', 'vieiraalice@gmail.com'),
('Carlos Eduardo Rezende', 'ceciliagoncalves@peixoto.br'),
('Elisa Ramos', 'mda-mota@campos.br'),
('Emanuelly Almeida', 'joana97@hotmail.com'),
('Maria Alice Rocha', 'gabrielly86@uol.com.br'),
('Sr. Samuel Duarte', 'sophieoliveira@gmail.com'),
('Dr. Thales Nascimento', 'catarinaazevedo@hotmail.com'),
('Maria Sophia Melo', 'hcastro@alves.com'),
('Milena da Costa', 'vferreira@cardoso.br'),
('Maria Alice Nascimento', 'cviana@bol.com.br'),
('Erick Gomes', 'pintoeduardo@pires.org'),
('Augusto Martins', 'theo56@farias.com'),
('Davi Cardoso', 'ceciliada-conceicao@hotmail.com'),
('Maysa Fernandes', 'maria-cecilia07@yahoo.com.br'),
('Maria Cecília da Cruz', 'lmonteiro@pereira.org'),
('Fernanda da Paz', 'pcavalcanti@uol.com.br'),
('Isabella Gonçalves', 'novaesmarcos-vinicius@gmail.com'),
('Nina Barros', 'sophie39@yahoo.com.br'),
('Pedro Miguel da Mota', 'leticiacastro@ig.com.br'),
('Amanda Lima', 'moreiranicole@hotmail.com'),
('Gustavo Martins', 'joaocostela@bol.com.br'),
('Dr. Davi Luiz Fernandes', 'rafaela51@uol.com.br'),
('Danilo das Neves', 'diego60@yahoo.com.br'),
('Ana Vitória Ramos', 'isis65@gmail.com'),
('Daniela Ribeiro', 'larissa31@jesus.br'),
('Daniel Barbosa', 'catarina11@teixeira.br'),
('Dr. Nicolas da Costa', 'rodrigueslaura@uol.com.br'),
('Arthur Moura', 'ppires@castro.br'),
('Melissa Moraes', 'mfreitas@ramos.net'),
('Maysa Aragão', 'luigi29@campos.net'),
('Isaac da Conceição', 'gustavo28@da.com'),
('Alice Costela', 'vitoria39@aragao.com'),
('Benjamin Costela', 'camposbruna@uol.com.br'),
('Sr. Levi Santos', 'silveiraotavio@araujo.com'),
('Juliana Pereira', 'epires@martins.com'),
('Cauê Freitas', 'ssouza@uol.com.br'),
('Maria Pinto', 'vieiramilena@pinto.br'),
('Dr. João Peixoto', 'ana-clara54@da.br'),
('Bryan Cardoso', 'vcastro@costela.com'),
('Maria Eduarda Melo', 'qmoraes@barros.org'),
('Gabriela Moraes', 'henriquerocha@cavalcanti.br'),
('Vitor Hugo Freitas', 'maraujo@araujo.com'),
('Samuel Lima', 'andre22@bol.com.br'),
('Juliana Campos', 'carvalhorafaela@nascimento.br'),
('João Lucas Lima', 'barroshenrique@hotmail.com'),
('Ana Beatriz Cardoso', 'fpereira@bol.com.br'),
('Kamilly Fogaça', 'monteiroana-julia@gomes.br'),
('Natália Lima', 'agathacaldeira@da.net'),
('Vitor Hugo Fernandes', 'erick07@ig.com.br'),
('Camila Costela', 'claramoraes@gmail.com'),
('Sarah Barbosa', 'ramosdavi-lucas@yahoo.com.br'),
('Lara Nunes', 'enzo60@yahoo.com.br'),
('Pedro Henrique Ramos', 'pintoenrico@hotmail.com'),
('Maria Sophia Nunes', 'vlima@das.br'),
('Breno Silva', 'sophiemonteiro@da.net'),
('Danilo Fernandes', 'kamillyda-costa@da.br'),
('Sophia Porto', 'heitor71@uol.com.br'),
('Marina Jesus', 'moraesclarice@gmail.com'),
('Lucas Gabriel Porto', 'mouramurilo@carvalho.br'),
('Maria Luiza Vieira', 'uda-mota@santos.com'),
('Levi Cavalcanti', 'santoslivia@hotmail.com'),
('Felipe Pires', 'thomasmoura@yahoo.com.br'),
('Júlia Mendes', 'caue51@gomes.org'),
('Dra. Maria da Costa', 'da-conceicaosamuel@yahoo.com.br'),
('Pietra Novaes', 'limahelena@melo.com'),
('Pietra Souza', 'xsilva@moreira.com'),
('Joaquim Rodrigues', 'guilhermeda-costa@goncalves.com'),
('Heloísa Costela', 'igorda-mata@ig.com.br'),
('Bárbara Pires', 'rmoreira@pires.br'),
('Luiz Otávio Duarte', 'xda-mota@ig.com.br'),
('Laura Rezende', 'hsantos@uol.com.br'),
('Eduardo Cunha', 'rochavinicius@bol.com.br'),
('Theo Silveira', 'davi-luiz24@silva.com'),
('Ana Laura das Neves', 'benjamin60@uol.com.br'),
('Isadora Duarte', 'mouralevi@gmail.com'),
('Sr. Theo Melo', 'brenogomes@cunha.br'),
('Mariana Almeida', 'fernandesleandro@vieira.com'),
('Erick Jesus', 'duarteana-beatriz@campos.com'),
('Maria Vitória Teixeira', 'melissada-conceicao@pereira.com'),
('Isabella Duarte', 'maria-ceciliacardoso@bol.com.br'),
('Sr. Luiz Miguel Viana', 'cribeiro@moura.org'),
('Srta. Isabella Campos', 'nicolecavalcanti@bol.com.br'),
('Sra. Beatriz Barbosa', 'luna27@ig.com.br'),
('Marina da Mata', 'ramosbreno@da.com'),
('Augusto Lopes', 'eviana@yahoo.com.br'),
('Vitor Gabriel da Mota', 'stella05@yahoo.com.br'),
('João Lucas Pinto', 'vnogueira@hotmail.com'),
('Olivia Sales', 'davi-luiz61@uol.com.br'),
('Carolina Viana', 'emanuel15@ig.com.br'),
('Henrique Porto', 'maria-sophiapires@yahoo.com.br'),
('Amanda Moraes', 'luiza01@ig.com.br'),
('Juliana Moreira', 'da-conceicaolara@azevedo.com'),
('Erick Moreira', 'mazevedo@hotmail.com'),
('Lavínia Moura', 'kcardoso@hotmail.com'),
('Isabelly Novaes', 'luiz-felipe10@ig.com.br'),
('Luiz Felipe Silveira', 'ferreirasophie@yahoo.com.br'),
('Sra. Clara Gomes', 'felipecunha@gmail.com'),
('Camila Pires', 'maria-cecilia51@jesus.com'),
('Dra. Pietra da Luz', 'felipeda-paz@hotmail.com'),
('Luiz Felipe Araújo', 'bianca82@bol.com.br'),
('Bernardo Lima', 'asouza@uol.com.br'),
('Ana Julia Costela', 'portobianca@ig.com.br'),
('Isabel Costela', 'ana-juliasantos@costa.com'),
('Davi Luiz da Cruz', 'ryansilveira@yahoo.com.br'),
('Fernando da Paz', 'leticiajesus@bol.com.br'),
('Ana Laura Santos', 'joaquimmendes@araujo.com'),
('Stella Ferreira', 'faraujo@jesus.br'),
('Rodrigo Nunes', 'scardoso@gmail.com'),
('Leonardo Peixoto', 'vda-rocha@bol.com.br'),
('Ian Lopes', 'wcostela@yahoo.com.br'),
('Maria Eduarda Cavalcanti', 'biancacosta@yahoo.com.br'),
('Elisa da Conceição', 'goncalvesvitor@farias.com'),
('Dr. Diogo da Cruz', 'tsales@uol.com.br'),
('Bryan Novaes', 'leandromoraes@gmail.com'),
('Gustavo Henrique Sales', 'esther01@uol.com.br'),
('Francisco Moreira', 'bryan60@bol.com.br'),
('Caroline Moreira', 'nogueiraclarice@uol.com.br'),
('Emilly Costa', 'novaesvinicius@moreira.com'),
('Otávio Silva', 'barbosabreno@hotmail.com'),
('Sra. Yasmin Ribeiro', 'larasilva@hotmail.com'),
('Dr. Davi Lucca Novaes', 'clarice88@uol.com.br'),
('Dra. Fernanda Ribeiro', 'rafael16@araujo.br'),
('Pietro Dias', 'hda-cunha@da.net'),
('Murilo Correia', 'pirespedro-lucas@da.br'),
('Srta. Júlia Santos', 'cunhaelisa@hotmail.com'),
('Giovanna Rocha', 'joao-felipe78@yahoo.com.br'),
('Isabella Ferreira', 'luiz-felipefreitas@bol.com.br'),
('Enzo Gabriel Jesus', 'maria-sophiarodrigues@yahoo.com.br'),
('Isabel Freitas', 'vianavitor-hugo@uol.com.br'),
('Sr. Gustavo Barbosa', 'monteiroana-luiza@ig.com.br'),
('Vinicius Rocha', 'estherfogaca@cunha.com'),
('Sarah Duarte', 'souzalevi@barros.br'),
('Sra. Ana Luiza Cunha', 'aliceribeiro@da.org'),
('Dr. Pedro Caldeira', 'emillyazevedo@peixoto.br'),
('Carolina Gonçalves', 'jesusisabel@melo.br'),
('Maria Cecília Souza', 'claricerezende@yahoo.com.br'),
('Carlos Eduardo Melo', 'tfernandes@alves.net'),
('Paulo Nunes', 'davi61@hotmail.com'),
('Lucca Martins', 'ferreiravitor@porto.org'),
('Rebeca Alves', 'maria-vitoria30@ig.com.br'),
('Lucas Gabriel Lima', 'tsantos@costa.org'),
('Sr. Enzo Gabriel Cunha', 'ana-vitoriamoura@uol.com.br'),
('Dra. Lorena Teixeira', 'maria-juliacardoso@souza.br'),
('Miguel Correia', 'isabellateixeira@da.br'),
('Rodrigo da Rocha', 'silvaana-livia@gmail.com'),
('Ana Silva', 'jcaldeira@uol.com.br'),
('Gabriela Aragão', 'alexandre39@gmail.com'),
('Kevin Monteiro', 'camposbrenda@gomes.com'),
('Vitor Peixoto', 'yporto@uol.com.br'),
('Rodrigo Viana', 'erick28@souza.com'),
('Srta. Agatha Aragão', 'bviana@bol.com.br'),
('Daniela Farias', 'henrique43@ig.com.br'),
('Arthur Peixoto', 'juancampos@azevedo.com'),
('Vicente Barbosa', 'idias@hotmail.com'),
('Daniel Santos', 'nicolelopes@bol.com.br'),
('Stella Martins', 'gustavo-henrique83@jesus.org'),
('Matheus da Luz', 'wbarros@ig.com.br'),
('Isis Souza', 'joliveira@yahoo.com.br'),
('Carolina Teixeira', 'levijesus@ig.com.br'),
('Lucas Gabriel Caldeira', 'isouza@uol.com.br'),
('Fernando da Rocha', 'portovicente@gmail.com'),
('Rebeca da Mota', 'vitor-gabriel99@cardoso.net'),
('Cecília Melo', 'da-rosajoao-miguel@ig.com.br'),
('Vinicius Rocha', 'agathaduarte@gomes.br'),
('Maria Alice Moraes', 'thiago87@uol.com.br'),
('Thiago Ribeiro', 'vicentelopes@uol.com.br'),
('Miguel das Neves', 'ferreiragabrielly@goncalves.com'),
('Isaac Dias', 'ceciliavieira@ig.com.br'),
('Heloísa Fernandes', 'kramos@ig.com.br'),
('Sr. Daniel Viana', 'evelyncaldeira@bol.com.br'),
('Breno Barros', 'ocunha@campos.net'),
('Laís Moura', 'brodrigues@teixeira.br'),
('Anthony Souza', 'arthur86@hotmail.com'),
('Caio Souza', 'joao-pedrosouza@moraes.org'),
('Ana Júlia Moura', 'sfarias@hotmail.com'),
('Rodrigo Cardoso', 'nunesvitor-hugo@vieira.br'),
('Pedro Miguel Alves', 'salesana-julia@castro.com'),
('Enrico Ribeiro', 'cardosomaria-luiza@yahoo.com.br'),
('Maria Fernanda Azevedo', 'arthur39@novaes.com'),
('Eduarda Nogueira', 'ycunha@ig.com.br'),
('Srta. Lívia Monteiro', 'pintolucas-gabriel@mendes.br'),
('Sr. Pedro Miguel Fogaça', 'wdias@bol.com.br'),
('Larissa da Mata', 'goncalvesluiz-felipe@ig.com.br'),
('Bruno Fogaça', 'vda-costa@lopes.br'),
('Bryan Almeida', 'wmoreira@yahoo.com.br'),
('Cauê Carvalho', 'jporto@cavalcanti.com'),
('João Gabriel Vieira', 'vitor04@nogueira.com'),
('Dra. Elisa Silveira', 'ida-cunha@jesus.org'),
('Bianca Campos', 'afreitas@rocha.com'),
('Dr. Felipe Sales', 'icavalcanti@almeida.br'),
('Dr. Isaac Pires', 'tcunha@yahoo.com.br'),
('Olivia da Paz', 'joao-gabriel65@yahoo.com.br'),
('Dra. Maysa Rodrigues', 'vitor-gabriel46@correia.net'),
('Maria Cecília da Mata', 'cda-rocha@campos.br'),
('Luna Cunha', 'luiz-fernandoda-costa@ig.com.br'),
('Vitória Nascimento', 'lrocha@teixeira.br'),
('Alícia Moreira', 'fariasmarcela@da.com'),
('Melissa Nunes', 'acavalcanti@gmail.com'),
('Enzo Gabriel Silva', 'zmoura@santos.com'),
('Sr. Lucca Cavalcanti', 'hcardoso@ig.com.br'),
('João Felipe Lima', 'hda-rocha@uol.com.br'),
('Dr. Caio Pires', 'daniel40@ig.com.br'),
('Anthony Mendes', 'oliviafarias@vieira.br'),
('Daniela Nunes', 'luizapinto@araujo.net'),
('Maria Sophia Pereira', 'da-rosajuan@yahoo.com.br'),
('Srta. Maria Julia Cavalcanti', 'pietro37@ferreira.br'),
('Maysa Lopes', 'wcorreia@yahoo.com.br'),
('Mariane da Luz', 'cunhapedro-lucas@gmail.com'),
('Henrique Correia', 'maria-vitoria28@peixoto.com'),
('Joana Pereira', 'steixeira@da.com'),
('Ian Porto', 'anthony72@nogueira.br'),
('Nina Rodrigues', 'krodrigues@gmail.com'),
('Alice das Neves', 'freitaslevi@bol.com.br'),
('Davi Luiz Ramos', 'correialuiz-otavio@bol.com.br'),
('Sr. Vitor Hugo Pires', 'vcavalcanti@jesus.org'),
('Sr. Leonardo Costa', 'ninamonteiro@da.com'),
('Emanuel Caldeira', 'juliana82@yahoo.com.br'),
('Sra. Evelyn Fogaça', 'raqueloliveira@freitas.com'),
('Srta. Elisa da Conceição', 'sabrinanovaes@uol.com.br'),
('Murilo Fogaça', 'eporto@ig.com.br'),
('João Silva', 'ana-vitoria75@bol.com.br'),
('Yago Carvalho', 'caue86@hotmail.com'),
('Clara Sales', 'miguel58@bol.com.br'),
('Miguel Rodrigues', 'barbosaeduardo@ig.com.br'),
('Alexia Costa', 'aramos@da.com'),
('Fernanda da Cruz', 'moreiraluiz-fernando@gmail.com'),
('Sr. Benjamin Novaes', 'ana-claracarvalho@ig.com.br'),
('Alexandre da Rosa', 'costelajulia@hotmail.com'),
('Nina Pires', 'mendeserick@costela.br'),
('Enzo Nogueira', 'cavalcantipedro-lucas@jesus.com'),
('Stephany Cunha', 'souzaheloisa@da.br'),
('Srta. Marina da Costa', 'fda-rosa@gmail.com'),
('Vitor Gabriel Costa', 'ana-clara52@hotmail.com'),
('Pedro Cardoso', 'stella04@silveira.br'),
('Pedro Barros', 'hnogueira@sales.com'),
('Dr. Cauê Nogueira', 'fernanda27@gmail.com'),
('Nicolas Campos', 'leandro00@santos.org'),
('Raquel Santos', 'fnunes@ig.com.br'),
('Maria Alice da Costa', 'limadavi-lucca@bol.com.br'),
('Davi Lucas Teixeira', 'tcampos@ig.com.br'),
('Sabrina Duarte', 'davipinto@ramos.com'),
('Raul da Luz', 'cunhamariana@da.br'),
('Manuela Ferreira', 'fernando41@melo.org'),
('Ana Clara Ferreira', 'gramos@caldeira.br'),
('Bárbara Moura', 'sophia19@dias.com'),
('André Farias', 'ymoreira@da.br'),
('Igor Farias', 'marcelo19@yahoo.com.br'),
('Luiz Fernando Barros', 'elisabarbosa@campos.br'),
('Yago Lima', 'vieiraana-vitoria@gmail.com'),
('Sr. Gustavo Jesus', 'lmoura@da.net'),
('Alexandre Oliveira', 'evelynmonteiro@melo.br'),
('Dra. Gabriela Cavalcanti', 'ana-beatrizrodrigues@da.org'),
('Augusto Dias', 'ana19@gmail.com'),
('Beatriz Novaes', 'pintomaria-alice@duarte.br'),
('Pietra Martins', 'ofogaca@gmail.com'),
('Daniel Cavalcanti', 'da-cunhaana-sophia@lopes.br'),
('Luiz Otávio Moraes', 'dlima@costa.com'),
('Rodrigo Jesus', 'pietroda-conceicao@farias.br'),
('Ana Beatriz Jesus', 'benicionunes@uol.com.br'),
('Sofia Vieira', 'rezendeemanuel@costa.net'),
('Eduardo Nunes', 'ferreiradavi-lucas@gmail.com'),
('Eduardo Pires', 'melofelipe@rezende.com'),
('Larissa Novaes', 'nascimentomaria-julia@uol.com.br'),
('João Gabriel da Rosa', 'matheus72@farias.org'),
('Júlia Vieira', 'carvalhomatheus@uol.com.br'),
('Kaique da Paz', 'nascimentostephany@rocha.br'),
('Dr. João Pedro Fogaça', 'lopesjuliana@araujo.br'),
('Isabella Dias', 'fariasmarcela@fogaca.com'),
('Murilo Nogueira', 'joao-gabrielduarte@bol.com.br'),
('Dr. Nicolas Araújo', 'heloisada-mota@uol.com.br'),
('Gabriela da Luz', 'carvalhocarlos-eduardo@hotmail.com'),
('Clarice Aragão', 'melolaura@hotmail.com'),
('Joaquim da Luz', 'aragaogustavo@bol.com.br'),
('Srta. Stephany Correia', 'mouramariane@ig.com.br'),
('Maria Sophia Castro', 'pedro22@ig.com.br'),
('Vitória Rodrigues', 'marinamoraes@hotmail.com'),
('Maria Sophia da Luz', 'nicole42@hotmail.com'),
('Srta. Pietra Novaes', 'kamillylopes@cavalcanti.br'),
('Srta. Eduarda Monteiro', 'luanacarvalho@ig.com.br'),
('Maysa Melo', 'ferreirakaique@hotmail.com'),
('Srta. Isabel Fernandes', 'barrosvitor@peixoto.com'),
('Luna Nascimento', 'ecastro@bol.com.br'),
('Sophie das Neves', 'zcardoso@goncalves.br'),
('Calebe Cardoso', 'vitor-gabrielda-cruz@ig.com.br'),
('Marcos Vinicius Carvalho', 'baraujo@ig.com.br'),
('Otávio Pinto', 'castrorafael@da.org'),
('Esther Jesus', 'barrosyuri@da.com'),
('Sr. Kevin Carvalho', 'gda-paz@gmail.com'),
('Davi Luiz Gonçalves', 'tcorreia@ribeiro.br'),
('Emanuella Carvalho', 'vicentenascimento@yahoo.com.br'),
('Levi Barbosa', 'qrezende@hotmail.com'),
('Miguel Caldeira', 'cardosomaria-clara@viana.br'),
('Daniela Vieira', 'asilveira@duarte.br'),
('Bruno Novaes', 'erickporto@da.com'),
('Kevin Cardoso', 'leticiada-conceicao@bol.com.br'),
('Ian Campos', 'jnovaes@freitas.br'),
('Yuri Silveira', 'peixotoheitor@hotmail.com'),
('Maria Sophia Castro', 'gomesesther@oliveira.org'),
('Milena Rodrigues', 'da-luzmarcos-vinicius@uol.com.br'),
('Pedro Henrique Nunes', 'smelo@barros.br'),
('Joaquim Jesus', 'caroline13@hotmail.com'),
('Vinicius Pires', 'natalia69@ig.com.br'),
('Diogo Pires', 'wrodrigues@caldeira.com'),
('Henrique Santos', 'stellasouza@bol.com.br'),
('Davi da Mota', 'fariasbernardo@barros.br'),
('Srta. Emilly Moura', 'rcosta@gmail.com'),
('João Lucas Rodrigues', 'brunavieira@yahoo.com.br'),
('Sr. Francisco Carvalho', 'nogueiracaio@hotmail.com'),
('Stephany da Rosa', 'maria-fernandada-rocha@oliveira.com'),
('Alana Ribeiro', 'juliaalves@fernandes.org'),
('Isis Monteiro', 'leandro74@ig.com.br'),
('Mariane Novaes', 'silvamaria-alice@gomes.org'),
('Ana Lívia Rocha', 'marcos-vinicius54@jesus.net'),
('Luiz Henrique Duarte', 'rlopes@araujo.org'),
('Juliana Nogueira', 'rodrigodas-neves@moraes.org'),
('Rafael da Mata', 'ribeirofernando@ig.com.br'),
('Thiago da Mata', 'das-nevesthales@hotmail.com'),
('Sra. Kamilly Melo', 'isis47@gmail.com'),
('Ana Beatriz Cardoso', 'claracosta@ig.com.br'),
('Marcela Jesus', 'da-costaguilherme@hotmail.com'),
('Dr. Miguel Ramos', 'melissa21@melo.com'),
('Sr. Alexandre Porto', 'sabrinada-cunha@bol.com.br'),
('Luigi Carvalho', 'zpereira@rocha.br'),
('Arthur Teixeira', 'antonio58@aragao.net'),
('Ryan Monteiro', 'emanuelnogueira@bol.com.br'),
('Gabriela da Cunha', 'jesusnathan@silveira.br'),
('Nina Cunha', 'wmoraes@hotmail.com'),
('João Aragão', 'nataliacostela@aragao.com'),
('Sr. João Miguel Fernandes', 'cavalcantimanuela@barros.com'),
('Laura Nascimento', 'bruna23@jesus.com'),
('Manuela Fogaça', 'gcavalcanti@gomes.com'),
('Catarina da Paz', 'theooliveira@yahoo.com.br'),
('Augusto Vieira', 'maria-sophiarocha@yahoo.com.br'),
('Alexandre Alves', 'salesheitor@silva.com'),
('Pedro Dias', 'luiz-miguel70@gmail.com'),
('Augusto Gonçalves', 'ana-clara11@gmail.com'),
('Daniel da Cunha', 'ana-laura94@ig.com.br'),
('João Lucas Mendes', 'nunesalana@fogaca.br'),
('Sra. Yasmin Peixoto', 'costelamaria@da.br'),
('Luana Pires', 'nmoraes@costela.br'),
('Juan Pires', 'ferreiramanuela@alves.net'),
('Heloísa Silveira', 'efarias@nogueira.com'),
('Mariana Barros', 'clariceribeiro@da.com'),
('Giovanna Duarte', 'caio83@bol.com.br'),
('Isis Nunes', 'ramosana-luiza@carvalho.br'),
('Gabrielly Costa', 'cavalcantialexia@uol.com.br'),
('Matheus Vieira', 'jesusdaniela@ramos.com'),
('Lorenzo Melo', 'melissa71@gmail.com'),
('Clarice Almeida', 'luana48@bol.com.br'),
('Sr. Augusto da Cunha', 'melissaoliveira@gmail.com'),
('Paulo da Paz', 'novaesleandro@da.br'),
('Vitor Gabriel Peixoto', 'portoana@sales.com'),
('Larissa Rocha', 'nicolecostela@nogueira.br'),
('Joana Peixoto', 'agatha54@cunha.com'),
('Maria Silva', 'maysa83@hotmail.com'),
('Pedro Henrique Gonçalves', 'marinada-luz@bol.com.br'),
('Olivia Martins', 'helena79@teixeira.org'),
('Alana Silveira', 'nascimentogustavo@caldeira.org'),
('Gustavo Henrique Fernandes', 'goncalvesjuan@moraes.com'),
('Nicole das Neves', 'danielagomes@ig.com.br'),
('Ana Beatriz Nascimento', 'jlopes@gmail.com'),
('Vinicius Fernandes', 'odas-neves@viana.net'),
('Srta. Evelyn Porto', 'da-matajoao-felipe@nascimento.br'),
('Matheus Ferreira', 'isisfernandes@melo.com'),
('Davi Lucas Martins', 'caroline98@cardoso.br'),
('Clarice da Mata', 'amandaviana@carvalho.br'),
('Enrico Melo', 'nicolas39@bol.com.br'),
('Maria Eduarda Alves', 'ana-livia39@barbosa.com'),
('Eloah Viana', 'silveirasophia@yahoo.com.br'),
('Yasmin Silva', 'sbarbosa@ig.com.br'),
('Igor Silva', 'da-cunhasophia@campos.net'),
('Lara Cavalcanti', 'vcardoso@araujo.br'),
('Bryan Cardoso', 'yasminfernandes@dias.br'),
('Lavínia Nunes', 'arthur61@bol.com.br'),
('Pedro Campos', 'moraesclara@goncalves.org'),
('Ana Laura Gomes', 'qnovaes@gmail.com'),
('Bruna Teixeira', 'rafaelanovaes@da.org'),
('Vitória Moura', 'felipebarbosa@novaes.com'),
('Emanuel Monteiro', 'jsilva@da.org'),
('Carlos Eduardo da Mata', 'evieira@campos.org'),
('Eduardo Rodrigues', 'fernando31@yahoo.com.br'),
('Ana Clara da Mota', 'vporto@bol.com.br'),
('Gabriela da Costa', 'ana-clara20@yahoo.com.br'),
('Yuri das Neves', 'thiago25@uol.com.br'),
('Lavínia Moraes', 'gvieira@hotmail.com'),
('Maria Cardoso', 'estherda-paz@yahoo.com.br'),
('Dra. Ana Julia Cardoso', 'nunessofia@azevedo.br'),
('Stephany da Costa', 'xdas-neves@bol.com.br'),
('Sra. Beatriz Rezende', 'gmoreira@duarte.com'),
('Beatriz Porto', 'heloisada-conceicao@moraes.com'),
('Vitor Hugo Rodrigues', 'ferreiravicente@barbosa.br'),
('Lorena Ramos', 'martinsemanuel@ferreira.com'),
('Milena Nascimento', 'silveiraluiz-fernando@uol.com.br'),
('Luiz Henrique Nunes', 'carolina79@gmail.com'),
('Beatriz Pires', 'davi-lucassilva@da.com'),
('Davi Lucca Moreira', 'amandamelo@rocha.br'),
('Cecília da Cruz', 'fariasbryan@hotmail.com'),
('Maria Sophia da Cruz', 'da-conceicaocarlos-eduardo@ferreira.br'),
('Maria Fernanda Aragão', 'da-rosaana-livia@bol.com.br'),
('Luana da Cunha', 'yda-conceicao@silva.br'),
('Maria Vitória Campos', 'inogueira@aragao.br'),
('Otávio Castro', 'yazevedo@carvalho.com'),
('Maria Cecília Almeida', 'cmoura@ig.com.br');
