INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (1, '86341029551', 'Lagoa de da Mota', '80', 'Dias Paulista', 'Acaiaca');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (2, '26587013902', 'Sítio Melo', '86', 'Dias', 'Céu Azul');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (3, '09753461216', 'Trevo da Mota', '463', 'Moraes', 'São Salvador');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (4, '47920681340', 'Lago Lívia Ferreira', '98', 'Cardoso', 'Barão Homem De Melo 2ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (5, '02581769467', 'Conjunto Luiz Felipe Moreira', '89', 'Pinto das Flores', 'Ermelinda');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (6, '14032586942', 'Favela de da Paz', '95', 'Sales do Amparo', 'Vila Madre Gertrudes 4ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (7, '37861250407', 'Conjunto Vitor Araújo', '82', 'Barbosa', 'Vila Calafate');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (8, '03849152723', 'Distrito da Mata', '234', 'Viana', 'São Vicente');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (9, '07591243888', 'Recanto de Moreira', '12', 'Oliveira de da Costa', 'Paquetá');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (10, '67492508158', 'Travessa Pinto', '7', 'da Luz do Galho', 'Conjunto Califórnia Ii');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (11, '87450136910', 'Lagoa Rocha', '70', 'Cardoso de Goiás', 'Vila Madre Gertrudes 4ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (12, '79368524173', 'Largo de Carvalho', '928', 'Duarte', 'Vila Nossa Senhora Do Rosário');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (13, '09786235410', 'Estação Oliveira', '46', 'Martins Verde', 'Flamengo');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (14, '21358490732', 'Ladeira da Conceição', '43', 'Almeida do Galho', 'Vista Do Sol');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (15, '40986573175', 'Travessa Isabelly Cardoso', '15', 'Melo', 'Alípio De Melo');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (16, '14038296750', 'Aeroporto Maria Julia Melo', '67', 'Dias', 'Nossa Senhora Da Conceição');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (17, '63579408100', 'Praia de da Mota', '8', 'Cunha de Silva', 'Embaúbas');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (18, '60248751930', 'Aeroporto de das Neves', '97', 'Porto de Pinto', 'São João');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (19, '49736581209', 'Residencial de Almeida', '2', 'da Cunha', 'XangriLá');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (20, '74320689500', 'Residencial de Lopes', '69', 'Viana', 'Jonas Veiga');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (21, '38740529150', 'Ladeira da Cruz', '91', 'da Costa do Sul', 'Vista Do Sol');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (22, '48061279304', 'Vereda Silveira', '880', 'Martins de Minas', 'João Pinheiro');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (23, '23415078914', 'Vereda da Luz', '313', 'Teixeira Alegre', 'Nossa Senhora De Fátima');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (24, '51704683262', 'Rodovia Clara Nascimento', '96', 'da Mota', 'Grotinha');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (25, '60147895375', 'Loteamento Alves', '9', 'Barbosa', 'Apolonia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (26, '65871249094', 'Jardim Bryan Fernandes', '84', 'Moreira do Oeste', 'Alto Dos Pinheiros');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (27, '53428170644', 'Trecho Nogueira', '68', 'Fernandes', 'Boa Esperança');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (28, '71408369575', 'Núcleo Ana Beatriz Carvalho', '785', 'Nunes da Prata', 'Novo Ouro Preto');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (29, '01486259758', 'Conjunto Freitas', '4', 'da Rocha', 'Vila Nova Gameleira 2ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (30, '87249630113', 'Pátio de da Luz', '3', 'da Mata', 'Vila Mangueiras');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (31, '86530174290', 'Loteamento Aragão', '69', 'da Costa', 'Vila Oeste');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (32, '70564139866', 'Área Maria Julia Alves', '90', 'Farias de Goiás', 'Vila Havaí');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (33, '24789610322', 'Viela Nogueira', '407', 'Teixeira', 'Leticia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (34, '31845620933', 'Jardim Bianca Porto', '1', 'Gonçalves', 'Novo Ouro Preto');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (35, '48106257967', 'Avenida Júlia Cardoso', '11', 'Freitas de Minas', 'Paraíso');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (36, '62870593465', 'Praia Nina Moraes', '82', 'Correia', 'Unidas');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (37, '04517639800', 'Distrito de das Neves', '82', 'Peixoto da Mata', 'São Jorge 2ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (38, '95217043652', 'Estação Ana Luiza Novaes', '6', 'Barros', 'São Paulo');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (39, '37428156017', 'Pátio de Cunha', '54', 'Cavalcanti de Almeida', 'Santa Rita');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (40, '39871024622', 'Alameda Laura Viana', '68', 'Melo', 'Conjunto Serra Verde');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (41, '61037852940', 'Morro de Cardoso', '10', 'Rodrigues de Viana', 'Nova Pampulha');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (42, '16583902702', 'Vale Teixeira', '29', 'Monteiro de Goiás', 'Conjunto Jardim Filadélfia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (43, '31724908669', 'Ladeira de Nogueira', '65', 'Almeida das Flores', 'Urca');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (44, '23670195840', 'Lago da Rosa', '12', 'Pinto', 'Vitoria');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (45, '67815029485', 'Quadra Yasmin Rezende', '379', 'da Luz do Sul', 'São Vicente');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (46, '26371450999', 'Pátio Cavalcanti', '70', 'Souza da Mata', 'Vila Copasa');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (47, '01583269460', 'Área Monteiro', '28', 'Ferreira dos Dourados', 'Vila Trinta E Um De Março');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (48, '45190763234', 'Viaduto de Mendes', '32', 'Cardoso do Norte', 'Nova Floresta');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (49, '89563072456', 'Fazenda Teixeira', '1', 'Ferreira do Galho', 'Marmiteiros');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (50, '70264395107', 'Estrada Alícia Nogueira', '145', 'das Neves de Fogaça', 'Caiçara  Adelaide');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (51, '20916384551', 'Viaduto Teixeira', '30', 'Farias', 'Baleia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (52, '21583469737', 'Núcleo de da Cunha', '932', 'Nunes do Norte', 'Maria Virgínia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (53, '45870621380', 'Jardim Caldeira', '70', 'Alves', 'Vila Santo Antônio');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (54, '32054681989', 'Praia de Costela', '41', 'Melo', 'Caiçaras');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (55, '83916750259', 'Ladeira Cardoso', '387', 'Mendes de Melo', 'Ouro Minas');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (56, '95483612728', 'Sítio de Carvalho', '186', 'Martins dos Dourados', 'Horto');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (57, '47106825930', 'Residencial Levi Carvalho', '48', 'Lopes de Minas', 'Morro Dos Macacos');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (58, '30175628408', 'Colônia Rodrigues', '325', 'Ferreira da Serra', 'Vila Nova Gameleira 3ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (59, '47026351826', 'Viaduto Lopes', '577', 'Rocha', 'Conjunto Lagoa');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (60, '91346027552', 'Fazenda de da Mota', '14', 'Rocha', 'Céu Azul');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (61, '56947213819', 'Morro Mendes', '27', 'Dias das Pedras', 'Vila Califórnia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (62, '86237105417', 'Passarela Almeida', '42', 'da Luz do Sul', 'Esplanada');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (63, '32690815451', 'Esplanada de Silva', '38', 'Nascimento de Mendes', 'Conjunto Santa Maria');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (64, '91542387655', 'Recanto Sales', '98', 'Campos', 'Jardim Alvorada');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (65, '81730694500', 'Loteamento João Rodrigues', '39', 'Rocha das Flores', 'Calafate');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (66, '80937642169', 'Setor Isabel Araújo', '334', 'Alves da Praia', 'Nossa Senhora Da Aparecida');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (67, '92748053656', 'Morro Lopes', '34', 'Souza', 'Monsenhor Messias');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (68, '68729534038', 'Área de Rocha', '223', 'Lopes', 'Rio Branco');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (69, '63192874031', 'Passarela da Paz', '582', 'Cardoso', 'Palmares');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (70, '91836407548', 'Via Catarina Peixoto', '338', 'da Conceição das Flores', 'São Marcos');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (71, '93845026774', 'Setor Duarte', '97', 'Rezende Alegre', 'São Jorge 3ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (72, '08695327400', 'Lago da Conceição', '95', 'Barbosa', 'Solimoes');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (73, '73289054683', 'Morro de Moura', '2', 'Vieira dos Dourados', 'Conjunto Santa Maria');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (74, '76305821968', 'Favela de Costela', '95', 'das Neves', 'Canadá');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (75, '69140583775', 'Ladeira Alves', '43', 'Nogueira do Oeste', 'Vila Vista Alegre');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (76, '29417635891', 'Largo Aragão', '69', 'Nogueira', 'Castelo');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (77, '80365794210', 'Trevo de da Mota', '9', 'Campos Verde', 'Tupi B');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (78, '70289456347', 'Setor Moreira', '820', 'Souza Paulista', 'Baleia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (79, '71854390279', 'Sítio de das Neves', '64', 'Azevedo', 'Braúnas');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (80, '74139052643', 'Jardim Azevedo', '62', 'Mendes Verde', 'Barão Homem De Melo 3ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (81, '81630274950', 'Alameda Maria Fernanda Ramos', '810', 'Azevedo', 'Funcionários');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (82, '14570396216', 'Estrada Guilherme da Conceição', '68', 'Costela do Norte', 'Camargos');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (83, '57192340634', 'Praça de Santos', '36', 'Cardoso', 'Marmiteiros');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (84, '20861547390', 'Quadra Helena Cardoso', '506', 'Nogueira de Pires', 'Cachoeirinha');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (85, '20354879197', 'Condomínio Mendes', '22', 'Almeida de Rocha', 'Distrito Industrial Do Jatoba');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (86, '80471953288', 'Praça Benjamin Teixeira', '165', 'Martins', 'Cinquentenário');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (87, '01824659342', 'Feira de Nogueira', '440', 'Silva', 'União');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (88, '20745186335', 'Praia Cunha', '64', 'Monteiro de Alves', 'João Alfredo');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (89, '01364589710', 'Setor de Alves', '1', 'Viana das Flores', 'Jatobá');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (90, '72168345937', 'Aeroporto Paulo Peixoto', '1', 'Gomes do Amparo', 'Vila Pinho');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (91, '74861395291', 'Avenida de Lopes', '51', 'Campos Alegre', 'Vila Nova Paraíso');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (92, '31758694084', 'Passarela de Jesus', '88', 'Cardoso de Cardoso', 'Serra');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (93, '91806534215', 'Largo de Almeida', '89', 'Martins de Gomes', 'Acaba Mundo');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (94, '19854760294', 'Trevo Pietro Araújo', '87', 'Peixoto Grande', 'Vila Jardim Montanhes');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (95, '85260179420', 'Rua Letícia Nogueira', '94', 'Alves de Jesus', 'Vila Paraíso');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (96, '14375026952', 'Lago de Moraes', '91', 'Moura de Caldeira', 'Jardim Montanhês');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (97, '04782956347', 'Largo de Cardoso', '7', 'Azevedo', 'Suzana');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (98, '06917238503', 'Recanto de Pereira', '40', 'Cavalcanti de Goiás', 'Delta');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (99, '20385761490', 'Via Enzo Gabriel Freitas', '29', 'Gonçalves do Sul', 'Castanheira');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (100, '94158072611', 'Pátio Santos', '50', 'Costa', 'Embaúbas');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (101, '37148265991', 'Condomínio de Pinto', '353', 'Ramos', 'Centro');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (102, '07984251649', 'Campo Bernardo Caldeira', '38', 'Souza de Cavalcanti', 'Havaí');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (103, '78340526910', 'Lago da Conceição', '74', 'Fogaça da Serra', 'Eymard');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (104, '21837045941', 'Rodovia Theo da Mota', '440', 'Nascimento de Azevedo', 'Pedreira Padro Lopes');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (105, '41689270322', 'Favela Fernandes', '92', 'Alves Alegre', 'Lourdes');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (106, '18093274588', 'Vale Luiz Felipe Barros', '9', 'Correia', 'Indaiá');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (107, '57240316980', 'Feira da Mata', '66', 'Castro', 'Mala E Cuia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (108, '60945812370', 'Favela de da Conceição', '939', 'Gomes de Campos', 'Boa União 2ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (109, '06281937503', 'Alameda Paulo Duarte', '396', 'Gomes', 'Aparecida 7ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (110, '14295683728', 'Rua da Rocha', '680', 'Costa de Goiás', 'Vila Sumaré');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (111, '80697453200', 'Alameda da Mata', '70', 'Sales de Lopes', 'Santa Cruz');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (112, '96304587139', 'Travessa de Almeida', '55', 'Pinto', 'Vila Mantiqueira');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (113, '80547193297', 'Passarela de Nunes', '79', 'Silveira', 'Alpes');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (114, '50347912850', 'Lagoa Luiz Fernando da Costa', '93', 'Costa', 'Vila São Gabriel');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (115, '29568041702', 'Fazenda Arthur da Rosa', '1', 'Pires', 'Caiçaras');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (116, '76492085167', 'Praça de Santos', '355', 'da Cruz', 'Vila Real 1ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (117, '05387249600', 'Passarela Lima', '51', 'Pires', 'Antonio Ribeiro De Abreu 1ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (118, '82376049113', 'Sítio de da Conceição', '648', 'Caldeira', 'Renascença');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (119, '15932478691', 'Vila Rafael Castro', '7', 'da Cunha', 'Novo Tupi');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (120, '27054961811', 'Loteamento Teixeira', '88', 'Porto do Galho', 'Vila Dos Anjos');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (121, '65947230143', 'Viela de Martins', '59', 'Peixoto', 'Pindura Saia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (122, '47158639282', 'Vereda Moreira', '350', 'Moura', 'Bom Jesus');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (123, '12907536877', 'Lago Freitas', '92', 'Duarte', 'Granja Werneck');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (124, '17834296078', 'Condomínio da Paz', '33', 'Ferreira Verde', 'Vila Jardim Alvorada');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (125, '25603789492', 'Vila Luigi Silveira', '70', 'Alves', 'Vila Madre Gertrudes 1ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (126, '13425078941', 'Travessa de Duarte', '45', 'Peixoto', 'Bonsucesso');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (127, '78960234583', 'Área Rezende', '18', 'da Rosa', 'Jardim Do Vale');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (128, '21073698440', 'Alameda de Jesus', '14', 'da Cruz de Costela', 'Glória');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (129, '50784361975', 'Condomínio Ana Lívia Santos', '77', 'Fernandes dos Dourados', 'Pantanal');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (130, '62371945846', 'Quadra de Campos', '69', 'Correia', 'Candelaria');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (131, '67294835128', 'Feira Eduardo da Costa', '7', 'da Paz da Prata', 'Betânia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (132, '04738615939', 'Fazenda da Rosa', '7', 'da Cruz das Pedras', 'Vila Sesc');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (133, '59306418205', 'Conjunto Nascimento', '44', 'Farias', 'Nossa Senhora De Fátima');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (134, '18237605977', 'Viaduto Bruna da Mata', '16', 'Costela de Ramos', 'Flamengo');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (135, '10483579297', 'Conjunto Davi Lucca Oliveira', '626', 'Rocha dos Dourados', 'Vila Antena Montanhês');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (136, '45236189098', 'Sítio de Vieira', '18', 'Nogueira', 'Nossa Senhora Da Conceição');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (137, '53902617470', 'Loteamento de Mendes', '26', 'Barros dos Dourados', 'Vila Da Amizade');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (138, '89546132764', 'Travessa Sabrina Melo', '72', 'Pinto da Mata', 'Cinquentenário');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (139, '36591480242', 'Avenida Eduarda Silva', '13', 'Moraes da Mata', 'Milionario');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (140, '26058439710', 'Colônia Moraes', '97', 'Sales', 'Alta Tensão 1ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (141, '59634780148', 'Colônia Maysa Silva', '15', 'da Costa', 'Vila São João Batista');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (142, '48216730969', 'Lagoa de Lima', '50', 'da Rocha de Goiás', 'Caiçara  Adelaide');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (143, '23958176003', 'Parque Cavalcanti', '5', 'Nascimento da Mata', 'Vila Ouro Minas');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (144, '28530164717', 'Trecho de Dias', '61', 'Aragão', 'Jardim Montanhês');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (145, '04137896593', 'Recanto Cardoso', '3', 'Rocha de da Conceição', 'Petropolis');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (146, '23796841031', 'Avenida de da Mata', '80', 'Costa Paulista', 'Aparecida 7ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (147, '27918603478', 'Conjunto da Mata', '16', 'Porto', 'União');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (148, '01245697307', 'Estrada da Rocha', '42', 'Silva de Pinto', 'Gameleira');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (149, '73148526937', 'Feira de da Costa', '263', 'Monteiro', 'Nova Vista');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (150, '04382567190', 'Esplanada Caldeira', '8', 'Jesus', 'São Sebastião');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (151, '02678149501', 'Área Maria Julia Dias', '88', 'Barros da Mata', 'Itaipu');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (152, '40798326565', 'Núcleo de Farias', '853', 'Pinto', 'Ipiranga');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (153, '83071295405', 'Vila Lara Pinto', '6', 'Barbosa do Campo', 'Caiçaras');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (154, '94150236780', 'Travessa Alves', '575', 'Freitas', 'Ermelinda');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (155, '50631472835', 'Viaduto Yago Silveira', '8', 'Farias Grande', 'Santa Rita');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (156, '37061829559', 'Residencial Manuela Rocha', '64', 'da Rosa do Oeste', 'Vitoria Da Conquista');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (157, '85062931460', 'Recanto de Alves', '16', 'Moraes', 'Nova Floresta');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (158, '51206397470', 'Vila Fogaça', '746', 'Nunes', 'Pedreira Padro Lopes');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (159, '20193876469', 'Residencial de da Cunha', '281', 'Martins de Azevedo', 'Braúnas');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (160, '72465380974', 'Feira Fernandes', '8', 'da Rocha Verde', 'Graça');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (161, '91075842611', 'Distrito Vieira', '8', 'Viana', 'Alto Barroca');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (162, '48235976056', 'Jardim João Guilherme Moraes', '62', 'Castro de Minas', 'Urca');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (163, '80596471211', 'Passarela Pereira', '448', 'Barbosa', 'Itapoa');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (164, '19687024313', 'Praia Thales Fernandes', '317', 'Silveira da Praia', 'Santa Sofia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (165, '28730159695', 'Residencial Rodrigues', '10', 'Barbosa de Moraes', 'Diamante');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (166, '42759160858', 'Chácara Duarte', '3', 'Novaes', 'Morro Dos Macacos');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (167, '16342875928', 'Trecho de da Cunha', '221', 'Costela do Norte', 'Zilah Sposito');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (168, '61302589415', 'Chácara de da Cruz', '96', 'Cardoso Alegre', 'Parque São Pedro');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (169, '42637895047', 'Passarela Breno Sales', '49', 'Azevedo da Prata', 'Vila Betânia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (170, '75823106912', 'Estrada de da Mota', '84', 'Moraes', 'Camponesa 2ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (171, '68295410342', 'Trevo Novaes', '57', 'Duarte de da Cunha', 'Eymard');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (172, '73195486075', 'Loteamento João Lima', '18', 'Pereira', 'Castanheira');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (173, '18047659375', 'Trevo Aragão', '2', 'Oliveira', 'Caetano Furquim');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (174, '79361048520', 'Pátio Francisco Jesus', '30', 'Cardoso', 'Lagoinha');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (175, '69740358101', 'Rua Leandro da Rosa', '7', 'Rodrigues de Goiás', 'Trevo');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (176, '93410528660', 'Jardim Thomas Rezende', '71', 'da Rocha', 'Vila Pinho');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (177, '31605874280', 'Viaduto Santos', '2', 'da Rosa', 'Miramar');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (178, '85623097456', 'Núcleo Pedro Araújo', '980', 'Santos', 'Vila Puc');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (179, '91427065802', 'Trevo Stephany Carvalho', '14', 'Silveira', 'Jardim Felicidade');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (180, '79325684128', 'Rodovia de Nunes', '21', 'Fernandes', 'Alta Tensão 2ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (181, '30814295797', 'Largo Barbosa', '101', 'Viana de Duarte', 'Vila Formosa');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (182, '64308921589', 'Colônia Gabriel Cavalcanti', '14', 'Melo', 'Aguas Claras');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (183, '23708659465', 'Viaduto Cauã Souza', '873', 'Nunes', 'Vila São Paulo');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (184, '01467925306', 'Praia Nunes', '120', 'Nogueira dos Dourados', 'Mirtes');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (185, '69348217500', 'Largo Oliveira', '40', 'Cardoso Verde', 'Bela Vitoria');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (186, '76582403974', 'Trecho Freitas', '1', 'da Luz', 'Vila Esplanada');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (187, '89650432124', 'Morro de Costela', '3', 'Viana', 'Jardim Guanabara');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (188, '95734860166', 'Condomínio da Mota', '470', 'Viana', 'Europa');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (189, '13257094680', 'Vila Thiago Moreira', '5', 'Barros', 'Túnel De Ibirité');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (190, '21035769859', 'Área Vieira', '52', 'da Cruz', 'Goiania');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (191, '48530629124', 'Praça Maria Fernanda Freitas', '842', 'Cardoso', 'Jaraguá');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (192, '36504891710', 'Distrito Oliveira', '27', 'da Conceição', 'Heliopolis');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (193, '18346079222', 'Loteamento Lorenzo Moura', '8', 'da Cruz', 'Vila Maloca');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (194, '39718265040', 'Vila Larissa Oliveira', '90', 'da Paz', 'Nossa Senhora Do Rosário');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (195, '39162874519', 'Praça de Freitas', '97', 'Ramos dos Dourados', 'Dom Silverio');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (196, '85704291341', 'Sítio da Rosa', '85', 'Barros da Prata', 'Vila Madre Gertrudes 1ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (197, '43502798656', 'Lago Pereira', '6', 'Pinto', 'Vila Atila De Paiva');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (198, '41986735273', 'Loteamento Helena Aragão', '28', 'Cunha', 'Vila Satélite');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (199, '87165349057', 'Travessa de Nascimento', '81', 'Fernandes da Mata', 'Vila Novo São Lucas');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (200, '03724815662', 'Setor de Barbosa', '881', 'Monteiro do Norte', 'Jardim América');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (201, '59136470848', 'Jardim de Ribeiro', '6', 'Farias', 'Túnel De Ibirité');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (202, '79386504120', 'Feira Campos', '5', 'Rezende', 'Dom Joaquim');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (203, '54839170657', 'Morro de Azevedo', '62', 'Silva do Galho', 'Leticia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (204, '51906734801', 'Esplanada Maria Cecília da Mata', '57', 'Rodrigues', 'Prado');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (205, '64890523774', 'Quadra Juliana Cavalcanti', '41', 'da Mata Paulista', 'Vila Dos Anjos');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (206, '98360124787', 'Colônia Sabrina Peixoto', '621', 'da Cunha dos Dourados', 'Boa União 2ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (207, '52780694149', 'Condomínio Nicole Fernandes', '21', 'Oliveira', 'Novo Santa Cecilia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (208, '74015968301', 'Núcleo da Rocha', '65', 'Gomes', 'Monsenhor Messias');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (209, '97563184066', 'Conjunto Azevedo', '85', 'Barros', 'Fernão Dias');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (210, '52410839797', 'Fazenda Lívia Nascimento', '11', 'Rocha', 'Bela Vitoria');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (211, '21950836460', 'Estação de da Cruz', '17', 'Moreira', 'Vila Madre Gertrudes 3ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (212, '15602748911', 'Largo de da Luz', '32', 'Pires da Praia', 'Guaratã');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (213, '70456293892', 'Viaduto de Peixoto', '918', 'Silva', 'Céu Azul');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (214, '78305962474', 'Estação Otávio Oliveira', '54', 'Fogaça do Oeste', 'Conjunto Taquaril');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (215, '23854017626', 'Largo de Souza', '24', 'Caldeira', 'Acaba Mundo');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (216, '45862137017', 'Lago Nascimento', '7', 'Cavalcanti', 'Pindura Saia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (217, '92617358003', 'Trecho Emanuella Rodrigues', '82', 'Cunha de Goiás', 'Copacabana');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (218, '20193546833', 'Avenida de da Paz', '7', 'Santos', 'Nova Cachoeirinha');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (219, '25019463752', 'Favela Diego Silveira', '71', 'da Rocha Verde', 'Dom Bosco');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (220, '61594730261', 'Vereda da Mota', '324', 'Cavalcanti', 'Lagoinha Leblon');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (221, '21039687512', 'Vereda de Ribeiro', '53', 'Costa Alegre', 'Vila Pilar');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (222, '82641950324', 'Colônia Nogueira', '84', 'Pires das Flores', 'Pindorama');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (223, '32748591682', 'Fazenda de Lopes', '12', 'Cardoso', 'Heliopolis');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (224, '72106593406', 'Campo de Fernandes', '63', 'Monteiro', 'Lagoinha');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (225, '04672185362', 'Rodovia Enzo Gabriel Vieira', '81', 'Rocha da Prata', 'Conjunto Paulo Vi');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (226, '81057324914', 'Chácara Daniela Castro', '227', 'da Costa de Porto', 'Santa Rita De Cássia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (227, '49825730692', 'Morro da Cruz', '53', 'Ferreira da Praia', 'Santa Cruz');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (228, '64307815262', 'Passarela Miguel Azevedo', '6', 'Costa do Amparo', 'Vera Cruz');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (229, '48192650758', 'Rodovia Moreira', '73', 'Costela', 'Baleia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (230, '45108793693', 'Lago Barbosa', '46', 'Moraes', 'Delta');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (231, '75821063930', 'Alameda Maitê Alves', '424', 'Lopes', 'Ambrosina');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (232, '10679354280', 'Viela Costa', '35', 'Alves de Alves', 'Pindorama');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (233, '67489203538', 'Morro das Neves', '44', 'Pereira de Goiás', 'Jardinópolis');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (234, '53260918795', 'Ladeira de Moraes', '56', 'Peixoto da Prata', 'Canadá');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (235, '13580942760', 'Viaduto de Melo', '40', 'Ferreira', 'Nossa Senhora Do Rosário');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (236, '74102398597', 'Estação Cavalcanti', '502', 'Rezende', 'Serrano');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (237, '12639075802', 'Viaduto Barros', '10', 'Nascimento', 'Corumbiara');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (238, '02139578686', 'Viela Ferreira', '65', 'Fogaça das Flores', 'Barroca');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (239, '90418263515', 'Distrito de Gonçalves', '83', 'Dias', 'Itapoa');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (240, '81574026380', 'Rua da Luz', '32', 'Rocha', 'Vila Nova');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (241, '78290136404', 'Travessa de da Rosa', '411', 'Rodrigues', 'Milionario');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (242, '47931862546', 'Largo Caldeira', '86', 'Ramos do Galho', 'Beira Linha');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (243, '50368927474', 'Praça Caio Silveira', '30', 'Caldeira de Campos', 'Jardim Alvorada');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (244, '71096825368', 'Setor Gomes', '92', 'Fogaça', 'Santo André');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (245, '69824071369', 'Estação de Campos', '39', 'Ferreira', 'Vila Independencia 1ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (246, '73495126864', 'Via da Mota', '1', 'Souza', 'Minas Brasil');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (247, '07384529123', 'Viela de Costa', '1', 'Cardoso de Lopes', 'Palmeiras');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (248, '95816024370', 'Via de Gomes', '3', 'da Mata de Rodrigues', 'Madri');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (249, '39087562438', 'Parque de Duarte', '63', 'Ribeiro', 'Outro');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (250, '85369742065', 'Loteamento Alves', '104', 'da Paz', 'Vila Pinho');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (251, '81239605498', 'Campo de da Rocha', '60', 'Teixeira do Sul', 'Buraco Quente');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (252, '09438152741', 'Quadra de Dias', '54', 'Costa', 'Grotinha');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (253, '98147260369', 'Quadra de da Mata', '30', 'Oliveira da Praia', 'Barreiro');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (254, '76843912087', 'Chácara Agatha Teixeira', '50', 'Moraes do Sul', 'Tirol');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (255, '04815276307', 'Vale Jesus', '26', 'da Costa', 'Coqueiros');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (256, '61872509401', 'Avenida Caldeira', '85', 'Fogaça de da Cruz', 'Vila Coqueiral');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (257, '01827953497', 'Ladeira Juliana Melo', '61', 'Teixeira', 'Virgínia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (258, '51376849291', 'Praia Martins', '34', 'Fogaça de Lima', 'Vila Engenho Nogueira');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (259, '06354718920', 'Trevo da Paz', '46', 'da Luz de Duarte', 'Alípio De Melo');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (260, '86047935265', 'Chácara de Barros', '428', 'Freitas dos Dourados', 'Laranjeiras');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (261, '92053786159', 'Distrito Ana Vitória da Mata', '142', 'Dias das Flores', 'Novo Glória');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (262, '61234958791', 'Avenida de Freitas', '703', 'Silva', 'Araguaia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (263, '45028193797', 'Área de Costela', '22', 'Mendes', 'Vila Betânia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (264, '89305421660', 'Conjunto Moura', '687', 'da Mata', 'Vila Santa Rosa');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (265, '09354678157', 'Viaduto de Gomes', '25', 'da Mota das Pedras', 'Jardim Leblon');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (266, '86713945066', 'Aeroporto Porto', '68', 'Rezende do Galho', 'Bernadete');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (267, '29056871420', 'Loteamento de da Conceição', '72', 'Caldeira de Peixoto', 'Vila Nova Paraíso');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (268, '76013925461', 'Conjunto de Vieira', '84', 'Pires de Porto', 'Engenho Nogueira');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (269, '89142756049', 'Vale das Neves', '72', 'Fogaça', 'São Paulo');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (270, '16590438757', 'Lagoa Correia', '64', 'Gomes do Amparo', 'Vila Maloca');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (271, '87123604571', 'Vereda Augusto Rezende', '7', 'Santos Verde', 'Floramar');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (272, '53902746106', 'Núcleo de Teixeira', '46', 'Aragão da Praia', 'Jardim Alvorada');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (273, '80376429178', 'Feira Esther da Costa', '88', 'Cunha de Freitas', 'Mineirão');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (274, '12609853777', 'Parque Sofia Silveira', '647', 'da Conceição de Barros', 'Santana Do Cafezal');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (275, '10295873612', 'Praia Pedro Lima', '241', 'Cavalcanti', 'Horto');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (276, '97142680520', 'Aeroporto de Lopes', '48', 'Rocha', 'São Gabriel');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (277, '78569312482', 'Rua Felipe Cavalcanti', '725', 'Nunes', 'Marieta 1ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (278, '19842360750', 'Esplanada de Caldeira', '97', 'Campos', 'Coração De Jesus');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (279, '73512946070', 'Setor Larissa Gonçalves', '1', 'Campos da Mata', 'Horto Florestal');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (280, '25716034853', 'Vale Raul Correia', '6', 'Silva da Prata', 'Bernadete');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (281, '03857412607', 'Via de Martins', '70', 'Monteiro', 'Caiçaras');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (282, '25938706130', 'Aeroporto da Conceição', '188', 'Gonçalves Paulista', 'Pirineus');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (283, '61354290780', 'Praia Fogaça', '5', 'da Cruz Grande', 'São Cristóvão');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (284, '15983046233', 'Estrada de Moreira', '1', 'Freitas de da Mota', 'Independência');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (285, '17623905821', 'Vila Pinto', '15', 'da Mata', 'Vila Jardim Montanhes');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (286, '82165973473', 'Trevo Monteiro', '127', 'Aragão', 'Carmo');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (287, '98273154637', 'Largo da Conceição', '12', 'Costa', 'Vila Madre Gertrudes 3ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (288, '85390627121', 'Vale de Carvalho', '57', 'Gomes do Norte', 'Vitoria Da Conquista');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (289, '64381079213', 'Campo Beatriz Mendes', '62', 'Ramos', 'Nossa Senhora Aparecida');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (290, '71548263982', 'Rodovia da Rosa', '28', 'Costela Alegre', 'Chácara Leonina');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (291, '01492368750', 'Travessa de Oliveira', '2', 'Jesus', 'Vila Nova Paraíso');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (292, '24153870960', 'Recanto de Aragão', '109', 'da Conceição', 'Coração Eucarístico');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (293, '13867409269', 'Lagoa Mariane Ferreira', '85', 'Ferreira de Viana', 'Maravilha');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (294, '10786324562', 'Jardim Costa', '45', 'Costela dos Dourados', 'Buraco Quente');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (295, '38120975405', 'Vereda Alana Barbosa', '56', 'Carvalho', 'Coração De Jesus');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (296, '54730821904', 'Passarela de Moreira', '7', 'das Neves do Sul', 'Trevo');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (297, '60125379480', 'Residencial de da Mata', '61', 'Ribeiro do Oeste', 'Estoril');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (298, '26781439022', 'Feira Barbosa', '91', 'da Mota da Mata', 'Buritis');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (299, '62918405370', 'Campo de Almeida', '527', 'da Cunha', 'Flamengo');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (300, '08751924323', 'Quadra de Sales', '67', 'Silva', 'Araguaia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (301, '34128650951', 'Vereda Pereira', '40', 'da Conceição Paulista', 'Cônego Pinheiro 2ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (302, '10286735903', 'Rua Calebe da Mata', '87', 'Correia', 'Vila Jardim Montanhes');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (303, '67530298186', 'Colônia Leandro Ferreira', '98', 'Moreira', 'Delta');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (304, '30864179510', 'Sítio de da Cunha', '40', 'Cardoso', 'Vila São João Batista');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (305, '54783916209', 'Núcleo de Castro', '699', 'da Cruz das Pedras', 'Castelo');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (306, '72906453161', 'Rua de Rezende', '92', 'Farias de Goiás', 'São Marcos');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (307, '76019543234', 'Estação de Alves', '1', 'Nascimento do Campo', 'Frei Leopoldo');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (308, '43978520141', 'Viela Caio Nascimento', '6', 'das Neves do Norte', 'Conjunto Paulo Vi');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (309, '58231706453', 'Quadra de Carvalho', '49', 'Ramos do Campo', 'Vila Boa Vista');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (310, '24873061903', 'Morro de Azevedo', '856', 'Viana', 'Vila Nossa Senhora Do Rosário');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (311, '16304852924', 'Sítio Danilo Silva', '76', 'da Paz Alegre', 'Granja Werneck');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (312, '78532906168', 'Jardim de Silveira', '7', 'Almeida', 'Tupi A');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (313, '92578413673', 'Alameda Sarah da Rosa', '6', 'Cardoso', 'São Benedito');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (314, '74835201671', 'Viaduto Pinto', '139', 'da Costa do Galho', 'Tirol');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (315, '14592708350', 'Praia de Duarte', '38', 'Costa de Sales', 'Concórdia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (316, '04351862726', 'Pátio da Costa', '99', 'Santos', 'Jardim Dos Comerciarios');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (317, '73148529600', 'Colônia Sabrina da Mata', '98', 'Fogaça', 'Flavio De Oliveira');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (318, '38061745984', 'Esplanada de da Cunha', '15', 'Pereira', 'Camponesa 2ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (319, '01698457294', 'Alameda Emanuelly Aragão', '9', 'da Rosa do Sul', 'Vila São Paulo');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (320, '28615347026', 'Travessa Monteiro', '27', 'da Conceição das Pedras', 'Palmares');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (321, '91780523432', 'Via de da Paz', '22', 'Nogueira de Novaes', 'Vila Madre Gertrudes 1ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (322, '36152087902', 'Alameda de Moraes', '85', 'Costela da Serra', 'São José');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (323, '57916480301', 'Via de Gonçalves', '69', 'Barros de Mendes', 'Pindorama');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (324, '05891624389', 'Condomínio Mariane Barbosa', '3', 'Monteiro Paulista', 'Camargos');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (325, '39540712823', 'Jardim de Viana', '78', 'Barros de Azevedo', 'Vila Da Paz');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (326, '65948723038', 'Aeroporto Rodrigues', '80', 'Caldeira', 'Barro Preto');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (327, '07132958488', 'Pátio de Nascimento', '90', 'Correia de Costa', 'Cenaculo');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (328, '14289056342', 'Aeroporto de da Paz', '63', 'Azevedo de Lima', 'Santo André');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (329, '47325018932', 'Via de Costela', '5', 'Azevedo', 'Santa Terezinha');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (330, '80417526911', 'Favela de Aragão', '11', 'da Luz', 'Braúnas');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (331, '43970568200', 'Fazenda de Caldeira', '17', 'Viana', 'Vila Antena Montanhês');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (332, '34857920638', 'Chácara Ana Júlia Ferreira', '54', 'Rodrigues', 'Vista Alegre');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (333, '08427659130', 'Distrito Dias', '97', 'Pinto', 'Renascença');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (334, '83471025626', 'Parque Jesus', '7', 'Campos de Nogueira', 'Inconfidência');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (335, '51624970370', 'Loteamento de Castro', '47', 'da Cruz', 'Parque São Pedro');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (336, '90875621368', 'Residencial Pires', '86', 'Peixoto', 'Vila Tirol');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (337, '29685347182', 'Morro de Moraes', '7', 'Campos do Norte', 'Vila São Gabriel Jacui');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (338, '74562938056', 'Ladeira Nascimento', '50', 'Jesus', 'Novo Das Industrias');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (339, '19026843542', 'Setor Davi Luiz Rezende', '4', 'Jesus da Mata', 'Maria Goretti');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (340, '50816937400', 'Recanto da Mata', '8', 'Farias Paulista', 'Embaúbas');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (341, '07821549304', 'Favela de da Costa', '4', 'Rezende de Lima', 'Vila Jardim São José');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (342, '39674205152', 'Rodovia de Cavalcanti', '39', 'Freitas', 'Paulo Vi');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (343, '65310294716', 'Viaduto Ana Lívia Peixoto', '62', 'Pereira', 'Guaratã');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (344, '35829617455', 'Jardim Rodrigues', '101', 'Nunes Paulista', 'Caetano Furquim');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (345, '96380752447', 'Vereda Maria Vitória Viana', '23', 'da Conceição de Araújo', 'Mangueiras');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (346, '04196537839', 'Trecho Ramos', '42', 'Freitas Alegre', 'Morro Dos Macacos');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (347, '86154230753', 'Largo Alexia Viana', '338', 'Carvalho', 'Esperança');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (348, '59407312879', 'Viaduto de Santos', '8', 'Vieira da Prata', 'Tiradentes');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (349, '79148560294', 'Vereda de Souza', '9', 'da Cruz', 'Vila Pinho');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (350, '90651247306', 'Esplanada Gomes', '45', 'Peixoto', 'Vila Real 1ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (351, '57621043890', 'Viela Luiz Gustavo das Neves', '98', 'Farias do Oeste', 'Álvaro Camargos');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (352, '58201497341', 'Viela Pinto', '8', 'da Costa das Pedras', 'Universo');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (353, '02913674887', 'Loteamento Ana Laura Costa', '13', 'Nascimento', 'Conjunto Celso Machado');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (354, '16240539716', 'Pátio de Correia', '3', 'Nogueira', 'Vila Dos Anjos');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (355, '46589307148', 'Área Rocha', '30', 'Nogueira Grande', 'Nossa Senhora Da Conceição');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (356, '21378549619', 'Vila Pedro Henrique Pires', '22', 'Porto do Oeste', 'Gameleira');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (357, '18463950701', 'Feira Freitas', '75', 'Silveira', 'Vila Calafate');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (358, '58736021407', 'Loteamento Luiz Otávio Lopes', '37', 'Costa', 'Jatobá');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (359, '13857692030', 'Sítio de Fogaça', '23', 'Souza da Mata', 'Lourdes');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (360, '59437186219', 'Setor Gomes', '44', 'Oliveira de Minas', 'Vila Jardim Montanhes');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (361, '12036984703', 'Rodovia João Vitor da Rocha', '9', 'Ribeiro', 'Jaraguá');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (362, '58197304610', 'Lago Carvalho', '46', 'Pinto', 'Vila Satélite');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (363, '72964105820', 'Largo Gomes', '89', 'da Rocha', 'Vila Da Luz');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (364, '84902175649', 'Rodovia Souza', '50', 'Sales', 'São Jorge 2ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (365, '34925807692', 'Ladeira de Pinto', '63', 'Ribeiro de Goiás', 'Cruzeiro');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (366, '57963018295', 'Condomínio de Freitas', '9', 'da Paz', 'Vila Da Luz');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (367, '85367910475', 'Rua das Neves', '4', 'da Paz do Oeste', 'Distrito Industrial Do Jatoba');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (368, '34812950732', 'Lagoa Nascimento', '601', 'Farias de Goiás', 'Boa Vista');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (369, '10758324626', 'Largo Igor da Cruz', '5', 'Martins', 'Piratininga');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (370, '78204693150', 'Sítio das Neves', '11', 'Fogaça Paulista', 'Vila Novo São Lucas');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (371, '76832501986', 'Campo Mendes', '1', 'Nascimento', 'Granja Werneck');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (372, '41369085206', 'Fazenda Ana Lima', '75', 'Pinto das Pedras', 'Santa Inês');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (373, '94620713813', 'Residencial Vinicius Correia', '546', 'das Neves', 'Araguaia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (374, '94572083150', 'Setor Eloah Oliveira', '147', 'Nascimento de Souza', 'Prado');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (375, '39406785110', 'Morro de Costa', '565', 'Pires dos Dourados', 'Monsenhor Messias');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (376, '02618537408', 'Largo de Correia', '30', 'Jesus da Mata', 'Vila Havaí');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (377, '61429538791', 'Jardim de da Paz', '8', 'Souza da Praia', 'Acaba Mundo');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (378, '05629481711', 'Estrada Oliveira', '5', 'da Luz', 'Vila Boa Vista');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (379, '25081967467', 'Lagoa de Cardoso', '296', 'da Mata', 'Indaiá');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (380, '61594378282', 'Estrada Isaac Costela', '530', 'Costa da Prata', 'Vila Madre Gertrudes 4ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (381, '01725864967', 'Trecho Almeida', '73', 'Novaes da Praia', 'Túnel De Ibirité');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (382, '14628039542', 'Conjunto de Souza', '39', 'Cunha', 'Flavio Marques Lisboa');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (383, '73096412804', 'Praça Heitor das Neves', '31', 'da Mota', 'Nossa Senhora Aparecida');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (384, '17084923560', 'Morro de Jesus', '12', 'Moraes', 'Padre Eustáquio');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (385, '21987650476', 'Chácara João Guilherme Campos', '13', 'Cardoso', 'Vila Nova Cachoeirinha 2ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (386, '06514829767', 'Praia Lopes', '23', 'Pinto Paulista', 'Silveira');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (387, '15378296455', 'Praia da Mota', '3', 'Pereira da Serra', 'Vila Nova Dos Milionarios');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (388, '98061752476', 'Quadra Isabelly Barbosa', '54', 'da Mata Alegre', 'São Damião');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (389, '48671523071', 'Trevo de Gonçalves', '981', 'Cardoso', 'Santa Margarida');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (390, '79106348548', 'Núcleo Davi Martins', '81', 'Ribeiro', 'Vila Coqueiral');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (391, '82059371686', 'Viela Moraes', '46', 'Correia da Serra', 'Floramar');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (392, '23170856995', 'Setor de Ferreira', '4', 'Moreira Alegre', 'Olhos água');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (393, '63142897500', 'Quadra de Ribeiro', '991', 'Cardoso', 'Barro Preto');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (394, '98147026501', 'Parque Anthony Nunes', '86', 'Gomes do Amparo', 'Boa Vista');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (395, '10793862469', 'Lago de Rodrigues', '32', 'Moraes das Pedras', 'São Luiz');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (396, '36971804520', 'Praça de Jesus', '85', 'da Costa', 'Vila Nova Gameleira 1ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (397, '19678425319', 'Aeroporto Lucca Gonçalves', '630', 'Martins', 'Vila Vista Alegre');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (398, '51824763964', 'Feira de Martins', '75', 'Pinto', 'Vila Nossa Senhora Do Rosário');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (399, '30724619534', 'Quadra Novaes', '12', 'da Mota', 'Santa Rosa');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (400, '36815290433', 'Distrito Thiago Teixeira', '12', 'Costa de Barros', 'Conjunto Capitão Eduardo');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (401, '50186479220', 'Viaduto Luiz Miguel Rodrigues', '6', 'Araújo de Goiás', 'Fernão Dias');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (402, '42097856365', 'Recanto Igor Martins', '2', 'Duarte', 'São Marcos');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (403, '84352760900', 'Jardim de Ribeiro', '92', 'Nunes', 'Senhor Dos Passos');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (404, '96372841096', 'Pátio de Novaes', '77', 'da Paz', 'Bandeirantes');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (405, '32480761517', 'Loteamento Ribeiro', '800', 'Moura', 'Nossa Senhora De Fátima');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (406, '71836052480', 'Estrada de Castro', '995', 'Santos de Goiás', 'Santa Maria');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (407, '25867041930', 'Trevo de Castro', '81', 'Ramos dos Dourados', 'Gutierrez');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (408, '72956348191', 'Rodovia Castro', '12', 'Correia', 'Vila Nova Gameleira 2ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (409, '21940687322', 'Alameda Moreira', '69', 'Porto', 'Juliana');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (410, '54816230726', 'Chácara de Lima', '88', 'Barros das Pedras', 'Suzana');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (411, '62471938582', 'Via Isabella Barros', '9', 'Cardoso', 'Vila Antena');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (412, '46270351871', 'Distrito Gustavo Henrique Porto', '61', 'Nunes', 'Maria Goretti');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (413, '72405698374', 'Conjunto Gomes', '9', 'Barros de da Cruz', 'Confisco');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (414, '52068941333', 'Avenida Moraes', '83', 'Silva Verde', 'Belmonte');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (415, '91235048624', 'Conjunto Vicente Costa', '242', 'Moura', 'Tiradentes');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (416, '03197825659', 'Avenida da Rocha', '8', 'Ferreira Grande', 'Santa Helena');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (417, '82734651017', 'Morro de Alves', '6', 'Souza da Praia', 'Vila Madre Gertrudes 4ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (418, '93058147600', 'Travessa de Campos', '600', 'da Cunha de Goiás', 'Barão Homem De Melo 1ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (419, '49136278564', 'Estrada Alves', '17', 'das Neves Paulista', 'Conjunto Califórnia I');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (420, '19806375475', 'Rodovia de Dias', '41', 'da Rosa de da Cunha', 'Grajaú');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (421, '19380276478', 'Praia Santos', '55', 'Monteiro', 'Vila Sesc');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (422, '42653108933', 'Recanto Catarina Lopes', '854', 'Farias da Mata', 'Maria Virgínia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (423, '32756019895', 'Esplanada Emilly Ramos', '41', 'da Paz', 'Copacabana');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (424, '30458761290', 'Estação Bruno Farias', '396', 'Barbosa de da Luz', 'Esperança');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (425, '18360942560', 'Trecho Rafael Nascimento', '395', 'Caldeira de da Rocha', 'Nova Esperança');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (426, '51308724950', 'Favela da Conceição', '63', 'da Conceição', 'Madri');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (427, '26198503470', 'Morro Novaes', '86', 'da Cunha de Cardoso', 'Aeroporto');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (428, '67145923882', 'Alameda Theo da Mota', '32', 'Rocha de Goiás', 'Vila Santo Antônio');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (429, '23791486519', 'Passarela de da Mota', '76', 'Cavalcanti de Barros', 'Novo Das Industrias');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (430, '63702149570', 'Quadra Carvalho', '8', 'da Rosa Paulista', 'Providencia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (431, '83714065253', 'Largo Yago Barbosa', '75', 'Rodrigues de Goiás', 'Pantanal');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (432, '47189065393', 'Morro de Viana', '20', 'Silva da Prata', 'Vila Madre Gertrudes 4ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (433, '65427831053', 'Núcleo Mariane Costa', '72', 'Mendes dos Dourados', 'Vila Jardim Montanhes');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (434, '84653791228', 'Feira de Gomes', '3', 'Ferreira da Mata', 'Distrito Industrial Do Jatoba');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (435, '17049632813', 'Trecho Dias', '555', 'Peixoto', 'Jaqueline');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (436, '36975428000', 'Jardim Sales', '49', 'Cardoso', 'Flavio De Oliveira');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (437, '46203791580', 'Pátio Lima', '9', 'da Mata', 'Conjunto Serra Verde');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (438, '20764398547', 'Pátio Clarice Rezende', '224', 'Lima do Sul', 'Vila Pilar');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (439, '24189630551', 'Favela Gonçalves', '27', 'da Luz do Norte', 'Heliopolis');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (440, '70964815249', 'Vila Marina das Neves', '12', 'Rodrigues das Pedras', 'Vila Calafate');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (441, '94601825342', 'Aeroporto de Novaes', '75', 'Caldeira', 'Virgínia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (442, '71985623455', 'Viaduto Murilo Novaes', '36', 'Aragão da Prata', 'Vitoria');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (443, '76850324900', 'Trecho de Jesus', '82', 'Barros de Nascimento', 'Nova Cintra');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (444, '78263941040', 'Via de Nascimento', '49', 'da Paz de da Rocha', 'Aparecida 7ª Seção');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (445, '59082164701', 'Lagoa de Souza', '64', 'Rocha Paulista', 'Vila Mantiqueira');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (446, '97051246801', 'Travessa Calebe Ramos', '14', 'Viana', 'Rio Branco');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (447, '29608745101', 'Morro Campos', '1', 'Cunha', 'Vila Rica');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (448, '16348702987', 'Vereda Carvalho', '45', 'da Mota', 'Serrano');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (449, '90758412304', 'Passarela Rodrigo da Cruz', '25', 'Cunha de Teixeira', 'São José');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (450, '20693418524', 'Colônia Miguel Lima', '21', 'Rezende', 'Ventosa');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (451, '63754102826', 'Sítio Moraes', '736', 'da Luz', 'Nova Granada');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (452, '53179680466', 'Largo de Oliveira', '7', 'Moura', 'Mariano De Abreu');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (453, '53269418051', 'Trecho de da Mota', '4', 'da Paz', 'Jaqueline');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (454, '57428693047', 'Estrada de Campos', '29', 'Pinto Verde', 'Floresta');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (455, '85149362042', 'Viaduto de Duarte', '9', 'Sales de Gomes', 'Serra');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (456, '43251896024', 'Rua Vicente Martins', '89', 'Oliveira', 'Satelite');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (457, '34680759283', 'Largo Araújo', '21', 'Gomes da Serra', 'Nova Gameleira');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (458, '90275461343', 'Trecho de Martins', '69', 'Fernandes', 'Vila Olhos água');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (459, '41923587609', 'Distrito Monteiro', '4', 'Novaes', 'Universo');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (460, '90247186350', 'Largo Moreira', '158', 'Moreira de Minas', 'Lagoa');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (461, '90651478294', 'Núcleo Thiago Moreira', '527', 'Carvalho Alegre', 'Planalto');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (462, '03745819675', 'Estrada de Duarte', '11', 'Almeida de da Cruz', 'Vila Sumaré');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (463, '79814502685', 'Residencial Carvalho', '80', 'da Rocha', 'Morro Dos Macacos');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (464, '94250716325', 'Aeroporto de Pereira', '40', 'da Luz', 'Novo Aarão Reis');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (465, '76053942170', 'Estrada Cauê Rocha', '50', 'da Rocha', 'Cardoso');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (466, '74829351004', 'Aeroporto Valentina Alves', '41', 'Cavalcanti', 'Itatiaia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (467, '91348706520', 'Campo de Dias', '91', 'da Mata', 'Aguas Claras');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (468, '12396708503', 'Trecho de Carvalho', '96', 'Campos dos Dourados', 'Bela Vitoria');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (469, '07142958685', 'Viela Araújo', '217', 'Viana', 'Cidade Jardim Taquaril');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (470, '60759148201', 'Rua Pereira', '66', 'Costa', 'São Luiz');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (471, '27085396121', 'Setor Yasmin Teixeira', '91', 'Ramos Grande', 'Cidade Jardim Taquaril');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (472, '80325679410', 'Sítio Juan das Neves', '740', 'Freitas', 'Vila Copasa');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (473, '03126875912', 'Residencial Caroline Moreira', '98', 'Caldeira', 'Novo São Lucas');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (474, '31846705975', 'Ladeira de Nogueira', '39', 'Santos do Norte', 'Vila São Dimas');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (475, '28017369450', 'Estrada de Nogueira', '379', 'Nunes de Goiás', 'Vila Sumaré');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (476, '84152309660', 'Parque de Farias', '34', 'Castro do Norte', 'Conjunto Taquaril');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (477, '04613782996', 'Residencial Carolina Martins', '293', 'da Luz de Cardoso', 'Nossa Senhora Do Rosário');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (478, '92837605492', 'Estrada de Monteiro', '35', 'Farias Paulista', 'Novo Aarão Reis');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (479, '08591347250', 'Alameda de da Rocha', '91', 'Jesus', 'Pindorama');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (480, '91620837404', 'Campo Barbosa', '2', 'Peixoto', 'Anchieta');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (481, '73219548032', 'Ladeira Laís Melo', '17', 'Farias das Flores', 'Aeroporto');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (482, '08246759167', 'Praia Ana Laura Souza', '3', 'Lima da Praia', 'Santa Cruz');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (483, '29863057177', 'Chácara Yuri Pinto', '8', 'Costa Grande', 'Vila Boa Vista');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (484, '81965402720', 'Vila Ana Luiza Monteiro', '52', 'Farias', 'Varzea Da Palma');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (485, '02579648356', 'Feira de Silva', '55', 'Almeida', 'Minaslandia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (486, '56271940811', 'Colônia de Viana', '426', 'Ribeiro de Correia', 'Senhor Dos Passos');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (487, '23954861089', 'Distrito Fogaça', '97', 'Campos', 'Pongelupe');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (488, '29561047802', 'Lagoa de Fogaça', '51', 'da Rocha', 'Vila Tirol');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (489, '60357942116', 'Feira de Duarte', '9', 'Caldeira da Serra', 'Esperança');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (490, '36718904287', 'Parque Alves', '34', 'Nascimento do Amparo', 'Coração De Jesus');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (491, '24906813704', 'Vereda de Barbosa', '8', 'Almeida', 'Caetano Furquim');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (492, '54170869249', 'Vila Rezende', '77', 'Dias', 'Parque São José');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (493, '52374819655', 'Morro Castro', '72', 'Moura', 'Palmares');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (494, '95670381475', 'Aeroporto de das Neves', '4', 'Barros', 'Cidade Jardim Taquaril');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (495, '05764382190', 'Via de Barbosa', '94', 'Lima das Flores', 'Vila Pilar');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (496, '32980746169', 'Fazenda Carvalho', '95', 'Porto do Campo', 'Oeste');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (497, '51764029399', 'Fazenda Laura Barros', '77', 'da Costa', 'Unidas');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (498, '95260134761', 'Alameda da Cunha', '440', 'Carvalho', 'Apolonia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (499, '63871249564', 'Quadra Moraes', '93', 'Peixoto de Goiás', 'Baleia');
INSERT INTO dados_usuario (id_usuario, cpf, logradouro, numero, cidade, bairro) VALUES (500, '50316792802', 'Estação Monteiro', '704', 'Araújo do Campo', 'Pindura Saia');